<!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></audio></button></canvas></datalist></details></dialog></iframe></listing></meter></noembed></noframes></noscript></optgroup></option></progress></rp></select></table></template></title></video>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Server Error</title>

<style>
    #nette-error {
        all: initial;
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        height: 70vh;
        min-height: 400px;
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 1000
    }

    #nette-error div {
        all: initial;
        max-width: 550px;
        background: white;
        color: #333;
        display: block
    }

    #nette-error h1 {
        all: initial;
        font: bold 50px/1.1 sans-serif;
        display: block;
        margin: 40px
    }

    #nette-error p {
        all: initial;
        font: 20px/1.4 sans-serif;
        margin: 40px;
        display: block
    }

    #nette-error small {
        color: gray
    }
</style>

<div id=nette-error>
    <div>
        <h1>Mrzí nás to ale nastala chyba</h1>

        <p>Omlouváme se ale vypadá to, že při překotném vývoji jsme nechali někde v kódu chybu</p>
        <p>Naštěstí už o tom víme a brzy chybu odstraníme a za pár minut bude vše v pořádku</p>

        <p>Pomoc vám zajistíme, ať už jste z kteréhokoli regionu či obce České republiky.<br/></p>
        <p><strong><a href="tel:800885599" class="phoneNumber">800 88 55 99</a></strong></p>
        <p>Volejte bezplatnou linku Sousedské pomoci!</p>

        <p><small>kód chyby 500</small></p>
    </div>
</div>

<script>
    document.body.insertBefore(document.getElementById('nette-error'), document.body.firstChild);
</script>
