name: 'App Build'

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    types: [opened, edited, synchronize, reopened]
    paths:
      - 'app/**.php'
      - '*.php'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Detecting PHP Code Standards Violations
        run: composer run-script phpcs

      - name: Detecting PHP Code Standards Violations
        run: composer run-script tests

      - name: Detecting PHP Code Standards Violations
        run: bin/console o:i

      - name: Send Slack notification
          uses: 8398a7/action-slack@v2
          if: failure()
          with:
            status: ${{ job.status }}
            author_name: ${{ github.actor }}
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
